package com.drakkens.ssm.events;

import com.direwolf20.buildinggadgets.common.items.AbstractGadget;
import com.direwolf20.buildinggadgets.common.tainted.building.BlockData;
import com.direwolf20.buildinggadgets.common.util.GadgetUtils;
import com.drakkens.ssm.commands.ResetMines;
import com.drakkens.ssm.mineallowancesystem.MineAllowanceManager;
import com.drakkens.ssm.mineallowancesystem.PlayerAllowanceConfig;
import com.drakkens.ssm.mineallowancesystem.PlayerMineAllowanceProvider;
import net.geforcemods.securitycraft.blocks.mines.ExplosiveBlock;
import net.minecraft.ChatFormatting;
import net.minecraft.Util;
import net.minecraft.network.chat.TranslatableComponent;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.common.util.FakePlayer;
import net.minecraftforge.event.RegisterCommandsEvent;
import net.minecraftforge.event.TickEvent;
import net.minecraftforge.event.TickEvent.Phase;
import net.minecraftforge.event.world.BlockEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.server.ServerLifecycleHooks;
import net.minecraftforge.server.command.ConfigCommand;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;

@EventBusSubscriber(modid = "ssm")
public class ModEvents {
    public static final String MESSAGE_NO_ALLOWANCE = "message.noallowance";
    public static final String MESSAGE_REMAINING = "message.allowance";
    private static MinecraftServer SERVER = ServerLifecycleHooks.getCurrentServer();

    public ModEvents() {
    }

    @SubscribeEvent
    public static void cancelMinePlacement(BlockEvent.EntityPlaceEvent event) {
        Entity var2 = event.getEntity();

        //Checking for player with Gadget in hands
        if (var2 instanceof Player player) {
            ItemStack gadget = null;


            /*TODO Can probably work with BlockSnapshots generated by the Gadgets instead?
            *   Use Gadget -> Creates BlockSnapshots with Air block.
            *
            */
            //TODO -> Check whether placing and subtracting is possible
            //Get Gadget
            if (player.getMainHandItem().getItem() instanceof AbstractGadget) {
                gadget = player.getMainHandItem();

            } else if (player.getOffhandItem().getItem() instanceof AbstractGadget) {
                gadget = player.getOffhandItem();

            }

            if (gadget != null) {
                BlockData gadgetTrueBlock = GadgetUtils.getToolBlock(gadget);

                if (gadgetTrueBlock.getState().getBlock() instanceof ExplosiveBlock) {
                    player.sendMessage(new TranslatableComponent("message.nogadgets").withStyle(ChatFormatting.RED), Util.NIL_UUID);
                    event.setCanceled(true);
                    return;

                }
            }
        }

        //Placing Mine Directly
        if (event.getPlacedBlock().getBlock() instanceof ExplosiveBlock) {
            //Check for Fake Player
            if (var2 instanceof FakePlayer) {
                event.setCanceled(true);
                return;
            }

            if (var2 instanceof Player player) {
                player.getCapability(PlayerMineAllowanceProvider.PLAYER_MINE_ALLOWANCE).ifPresent((playerMineAllowance) -> {
                    if (playerMineAllowance.getMineAllowance() == 0) {
                        player.sendMessage((new TranslatableComponent(MESSAGE_NO_ALLOWANCE)).withStyle(ChatFormatting.RED), Util.NIL_UUID);
                        event.setCanceled(true);
                    } else if (playerMineAllowance.getMineAllowance() == 1) {
                        playerMineAllowance.subtractMineAllowance(1);
                        player.sendMessage((new TranslatableComponent(MESSAGE_NO_ALLOWANCE)).withStyle(ChatFormatting.YELLOW), Util.NIL_UUID);
                    } else {
                        playerMineAllowance.subtractMineAllowance(1);
                        player.sendMessage((new TranslatableComponent(MESSAGE_REMAINING, playerMineAllowance.getMineAllowance())).withStyle(ChatFormatting.GREEN), Util.NIL_UUID);
                    }
                });
            }
        }
    }

    @SubscribeEvent
    public static void resetPlayerMines(TickEvent.ServerTickEvent event) {
        if (SERVER == null) {
            SERVER = ServerLifecycleHooks.getCurrentServer();
        }

        if (event.phase != Phase.END) {
            LocalDate currentDate = LocalDate.now();
            LocalDate lastResetDate = MineAllowanceManager.getData(SERVER).lastResetToDate();
            if (!currentDate.equals(lastResetDate)) {
                List<ServerPlayer> players = SERVER.getPlayerList().getPlayers();

                for (ServerPlayer player : players) {
                    player.getCapability(PlayerMineAllowanceProvider.PLAYER_MINE_ALLOWANCE).ifPresent((playerMineAllowance) -> playerMineAllowance.setMineAllowance(PlayerAllowanceConfig.DAILY_MINES.get()));
                    MineAllowanceManager.getData(SERVER).setLastReset(currentDate.atStartOfDay().atZone(ZoneId.systemDefault()).toInstant().toEpochMilli());
                }
            }
        }
    }

    @SubscribeEvent
    public static void registerCommands(RegisterCommandsEvent event) {
        new ResetMines(event.getDispatcher());
        ConfigCommand.register(event.getDispatcher());
    }
}
